version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  nginx:
    build: ./hotstar-clone
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:v0.27.0
    ports:
      - "9115:9115"
    command:
      - --config.file=/etc/blackbox_exporter/config.yaml
    volumes:
      - ./blackbox/config.yaml:/etc/blackbox_exporter/config.yaml:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.7.2
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus/alerts.yaml:/etc/prometheus/alerts.yaml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - blackbox
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.28.1
    volumes:
      - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yaml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    networks:
      - monitoring

  webhook:
    build: ./webhook
    ports:
      - "5001:5001"
    volumes:
      - ./playbooks:/playbooks:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - alertmanager
    networks:
      - monitoring

