groups:
  - name: host-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has CPU usage above 80% for 2 minutes."

      - alert: DiskRunningFull
        expr: (node_filesystem_avail_bytes{fstype=~"ext.*|xfs", mountpoint="/"} * 100) / node_filesystem_size_bytes{fstype=~"ext.*|xfs", mountpoint="/"} < 20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk running full on {{ $labels.instance }}"
          description: "Free disk space is below 20% on {{ $labels.mountpoint }}."

      - alert: NodeExporterDown
        expr: up{job="node"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter has been down for more than 1 minute."
